Traceback (most recent call last):
  File "C:\Users\sotiris\AppData\Local\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\sotiris\AppData\Local\anaconda3\Lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sotiris\AppData\Local\anaconda3\Lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sotiris\AppData\Local\anaconda3\Lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sotiris\AppData\Local\anaconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\sotiris\AppData\Local\anaconda3\Lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\sotiris\AppData\Local\anaconda3\Lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\sotiris\AppData\Local\anaconda3\Lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from scipy import signal
import scipy.io.wavfile
# ŒëŒΩŒ±œÑœÅŒ≠ŒæœÑŒµ œÉœÑŒ∑ŒΩ œÑŒµŒ∫ŒºŒ∑œÅŒØœâœÉŒ∑ œÑŒ∑œÇ Œ≤ŒπŒ≤ŒªŒπŒøŒ∏ŒÆŒ∫Œ∑œÇ scipy.signal
# https://docs.scipy.org/doc/scipy/reference/signal.html
from scipy.fft import fft, fftfreq
from dash import Dash, dcc, html, Input, Output
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
from numpy import random
import pandas
import plotly
import plotly.express as px
import plotly.graph_objs as go
import dash_bootstrap_components as dbc
import warnings
warnings.filterwarnings('ignore')
print("Libraries added successfully!")
------------------

[1;31m---------------------------------------------------------------------------[0m
<<<<<<< HEAD
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[4], line 6[0m
[0;32m      3[0m [38;5;66;03m# ŒëŒΩŒ±œÑœÅŒ≠ŒæœÑŒµ œÉœÑŒ∑ŒΩ œÑŒµŒ∫ŒºŒ∑œÅŒØœâœÉŒ∑ œÑŒ∑œÇ Œ≤ŒπŒ≤ŒªŒπŒøŒ∏ŒÆŒ∫Œ∑œÇ scipy.signal[39;00m
[0;32m      4[0m [38;5;66;03m# https://docs.scipy.org/doc/scipy/reference/signal.html[39;00m
[0;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfft[39;00m [38;5;28;01mimport[39;00m fft, fftfreq
[1;32m----> 6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdash[39;00m [38;5;28;01mimport[39;00m Dash, dcc, html, Input, Output
[0;32m      7[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m
[0;32m      8[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
=======
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[21], line 57[0m
[0;32m     55[0m fig[38;5;241m.[39mshow(renderer[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnotebook[39m[38;5;124m'[39m)
[0;32m     56[0m [38;5;66;03m# Convert figure to HTML[39;00m
[1;32m---> 57[0m fig_html [38;5;241m=[39m [43mpio[49m[38;5;241m.[39mto_html(fig, full_html[38;5;241m=[39m[38;5;28;01mFalse[39;00m, include_plotlyjs[38;5;241m=[39m[38;5;124m'[39m[38;5;124mcdn[39m[38;5;124m'[39m)
[0;32m     58[0m display(HTML(fig_html))
>>>>>>> fe66cec273e0b720f222b665b24f51f6af8b0116

[1;31mModuleNotFoundError[0m: No module named 'dash'
ModuleNotFoundError: No module named 'dash'

